version: 2.1
executors:
      docker-publisher:
        environment:
          IMAGE_NAME: rahulh25/covid19-dashboard:4.0
        docker:
          - image: circleci/buildpack-deps:stretch
orbs:
  node: circleci/node@1.1.6
  aws-eks: circleci/aws-eks@0.2.7
  kubernetes: circleci/kubernetes@0.11.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run-script test
  build:
      executor: docker-publisher
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Docker image
            command: |
              docker build -f Dockerfile -t $IMAGE_NAME .
        - run:
            name: Archive Docker image
            command: docker save -o image.tar $IMAGE_NAME
        - persist_to_workspace:
            root: .
            paths:
              - ./image.tar
  publish-latest:
        executor: docker-publisher
        steps:
          - attach_workspace:
              at: /tmp/workspace
          - setup_remote_docker
          - run:
              name: Load archived Docker image
              command: docker load -i /tmp/workspace/image.tar
          - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker push $IMAGE_NAME
  test-cluster:
        executor: aws-eks/python3     
        steps:
          - update-kubeconfig-with-authenticator:
              aws-profile: rahulh25
              aws-region: us-east-2
              cluster-name: covidcluster
              install-kubectl: true
          - kubernetes/update-container-image:
              container-image-updates: "rahulh25/covid19-dashboard:3.0=rahulh25/covid19-dashboard:4.0"
              get-rollout-status: false
              record: true
              resource-name: deployment/covid19dashboard
              show-kubectl-command: false
              watch-rollout-status: true
workflows:
    build-and-test:
      jobs:
        - build-and-test
    build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: master
          - publish-latest:
              requires:
                - build
              filters:
                branches:
                  only: master
    change-image-in-eks:
        jobs:
          - test-cluster:
              requires:
                - build
